version: '3.9' 

services:

  postgres:

    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./env/.postgres_env
    networks:
      - employee_app_network
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    restart: unless-stopped  


  adminer:
        image: adminer
        environment:
            - ADMINER_DESIGN=pappu687
        depends_on:
            - postgres
        networks:
            - employee_app_network
        volumes:
            - adminer:/adminer
        ports:
            - 8080:8080
        restart: on-failure


  django:

    build:
      context: ./django/
      dockerfile: 'DockerFile'
    

      


    depends_on:
      - postgres 

    volumes:
        - ./django:/app
        - static-files:/app/static

    links:
      - postgres:postgres

    ports:
      - 5000:5000

    env_file:
      - ./env/.env

    networks:
      - employee_app_network  


    restart: always


volumes:

    static-files:
        name: employee_app_django_static_volume

    postgresdata:
        name: employee_app_postgres_volume

    adminer:
        name: employee_app_adminer_volume    
    




networks:
    employee_app_network:
        name: supernet
        external: True  